stages:
  - build_db

building:
  stage: build_db
  script:
    - echo "A new file in the ./chunks folder has changed!"
    # Add your processing commands here
  rules:
    - changes:
        - chunks/**