"""The submission template, generated from the field registry.

Two files, one declaration. ``template.tsv`` is the machine-readable form; ``template.xlsx`` is the
one most submitters open, and it carries the three things a plain `.tsv` cannot:

* **every cell formatted as Text.** This is not decoration. ``method.frequency`` holds `50/67` and a
  V call holds `TRAV12-2*01`; Excel turns the first into a date and can mangle the second the moment
  a column is typed as General. The retired `template.xls` protected them exactly this way - all 165
  of its data cells carried number format ``@`` - and losing that protection is how a submission
  arrives with a column of 1967 dates in it.
* **the header coloured by column group**, which is how a submitter sees at a glance which columns
  are required. The four colours are read off the retired `template.xls` so the file looks like the
  one people have been using since 2016, not like a new one.
* **a second sheet describing every column**, from the registry's own ``comment``, so the
  description cannot drift from the build the way the old spreadsheet's did.

The retired `.xls` was a 2016 `Composite Document File V2`, code page 1251, readable only with
`xlrd`. It was one of the nine places this package's docstring lists as having already drifted, and
it had: its examples wrote ``antigen.species = HIV`` where the vocabulary now says ``HIV-1``.
"""
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from .fields import CHUNK_COLUMNS, FIELDS

if TYPE_CHECKING:  # pragma: no cover - typing only
    from collections.abc import Sequence

#: Header fill per column group, read off the retired ``template.xls`` so the regenerated file looks
#: like the one submitters know. `chunk.id` grey, the required complex columns peach, `method.*`
#: pale yellow, `meta.*` pale green.
GROUP_FILLS: tuple[tuple[str, str], ...] = (
    ("chunk.", "C0C0C0"),
    ("method.", "FFFFCC"),
    ("meta.", "CCFFCC"),
)
#: Everything not matched above: the complex-information columns, which are the required ones.
REQUIRED_FILL = "FFCC99"


#: Where the full per-column guidance lives. The registry's ``comment`` is what ``vdjdb.meta.txt``
#: ships and `vdjdb-web` displays, and it is thin or absent on the chunk-only columns - 10 of the 33
#: carry one. The prose that says how to *fill* each column is the specification page, so the guide
#: sheet names it rather than pretending the registry has it.
SPECIFICATION = "https://docs.isalgo.dev/vdjdb-db/standards/chunk-format.html"

#: What each example row demonstrates, shown as a note on its ``chunk.id`` cell. Parallel to
#: :data:`EXAMPLES`; a mismatch in length is a declaration error and raises.
EXAMPLE_NOTES: tuple[str, ...] = (
    "A paired human class I record with a solved structure. Both chains of one clone are columns "
    "of the SAME row - never two rows.",
    "A paired class II record: mhc.a and mhc.b are both real alleles, not B2M.",
    "A beta-only record. Leave the alpha CDR3, V and J blank when the chain is unknown; the record "
    "is still kept.",
    "An alpha-only mouse record. species uses the CamelCase vocabulary - MusMusculus, not "
    "'mouse' or 'Mus musculus'.",
)

#: Rows of Text-formatted cells beyond the examples, so a submitter typing into an empty row gets
#: the same protection the examples have. Without it Excel types the first thing typed into a fresh
#: cell as General and turns `50/67` into a date.
BLANK_ROWS = 100

#: Four example records, one per shape a submission takes. Each is a real curated row, so every
#: value passes `vdjdb qc` and none teaches a spelling the vocabulary rejects - which the retired
#: `template.xls` did, writing `antigen.species = HIV` where the corpus says `HIV-1`.
#:
#: A committed, reviewed constant rather than a read of `chunks/`: the template is regenerated by
#: its own pull request and must not change because an unrelated chunk landed.
EXAMPLES: tuple[dict[str, str], ...] = (
    # a paired human class I record, with a solved structure (from chunks/PDB_Database.txt)
    {
        'chunk.id': '1',
        'cdr3.alpha': 'CAVTTDSWGKLQF',
        'v.alpha': 'TRAV12-2*01',
        'j.alpha': 'TRAJ24*01',
        'cdr3.beta': 'CASRPGLAGGRPEQYF',
        'v.beta': 'TRBV6-5*01',
        'j.beta': 'TRBJ2-7*01',
        'species': 'HomoSapiens',
        'mhc.a': 'HLA-A*02:01:59',
        'mhc.b': 'B2M',
        'mhc.class': 'MHCI',
        'antigen.epitope': 'LLFGYPVYV',
        'antigen.gene': 'Tax',
        'antigen.species': 'HTLV-1',
        'reference.id': 'PMID:8906788',
        'method.identification': 'structural',
        'method.verification': 'structural',
        'meta.structure.id': '1AO7',
    },
    # a paired class II record: mhc.a and mhc.b are both real alleles (from chunks/Jupudi_2025_Ro60.txt)
    {
        'chunk.id': '2',
        'cdr3.alpha': 'CAVNSGNNNDMRF',
        'v.alpha': 'TRAV8-1',
        'j.alpha': 'TRAJ43',
        'cdr3.beta': 'CASSEAAAYYGYTF',
        'v.beta': 'TRBV2',
        'j.beta': 'TRBJ1-2',
        'species': 'HomoSapiens',
        'mhc.a': 'HLA-DRA*01',
        'mhc.b': 'HLA-DRB1*03:01',
        'mhc.class': 'MHCII',
        'antigen.epitope': 'PCPVTTDMTLQQVLM',
        'antigen.gene': 'TROVE2',
        'antigen.species': 'HomoSapiens',
        'reference.id': 'PMID:41424382',
        'method.identification': 'antigen-loaded-targets',
        'method.frequency': '2/95',
        'method.singlecell': 'yes',
        'method.sequencing': 'sanger',
        'method.verification': 'antigen-loaded-targets,direct',
        'meta.cell.subset': 'CD4+',
        'meta.subject.cohort': "Sjogren's Disease",
        'meta.clone.id': '4A',
        'meta.epitope.id': 'P106',
        'meta.tissue': 'Salivary Gland',
    },
    # a beta-only record that names its D segment (from chunks/PMID_18270323.txt)
    {
        'chunk.id': '3',
        'cdr3.beta': 'CASRPGTASYEQYF',
        'v.beta': 'TRBV28*01',
        'd.beta': 'TRBD1*01',
        'j.beta': 'TRBJ2-7*01',
        'species': 'HomoSapiens',
        'mhc.a': 'HLA-B*35:08',
        'mhc.b': 'B2M',
        'mhc.class': 'MHCI',
        'antigen.epitope': 'CPSQEPMSIYVY',
        'antigen.gene': 'pp65',
        'antigen.species': 'CMV',
        'reference.id': 'PMID:18270323',
        'method.identification': 'pentamer-sort',
        'method.frequency': '2/7',
        'method.sequencing': 'sanger',
        'meta.cell.subset': 'CD8+',
        'meta.subject.cohort': 'healthy',
        'meta.subject.id': '1',
        'meta.tissue': 'Polyclonal T-cell line',
    },
    # an alpha-only mouse record (from chunks/PMID_28934479.txt)
    {
        'chunk.id': '4',
        'cdr3.alpha': 'CAMRDSNYQLIW',
        'v.alpha': 'TRAV16D/DV11',
        'j.alpha': 'TRAJ33',
        'species': 'MusMusculus',
        'mhc.a': 'H2-Db',
        'mhc.b': 'B2M',
        'mhc.class': 'MHCI',
        'antigen.epitope': 'KAVYNFATC',
        'antigen.gene': 'GPC',
        'antigen.species': 'LCMV',
        'reference.id': 'PMID:28934479',
        'method.identification': 'tetramer-sort',
        'method.frequency': '1/86',
        'method.singlecell': 'yes',
        'method.sequencing': 'rna-seq',
        'meta.subject.cohort': 'C57BL/6 immunized with LCMV',
    },
)


def _fill(column: str) -> str:
    for prefix, colour in GROUP_FILLS:
        if column.startswith(prefix):
            return colour
    return REQUIRED_FILL


def header_line() -> str:
    """The template's header, which is :data:`CHUNK_COLUMNS` and nothing else."""
    return "\t".join(CHUNK_COLUMNS)


def write_tsv(path: Path, examples: Sequence[dict[str, str]] = ()) -> Path:
    """The tab-separated template."""
    rows = [header_line()]
    rows += ["\t".join(row.get(c, "") for c in CHUNK_COLUMNS) for row in examples]
    path.write_text("\n".join(rows) + "\n")
    return path


def write_xlsx(path: Path, examples: Sequence[dict[str, str]] = ()) -> Path:
    """The Excel template: text-formatted cells, group-coloured header, and a column guide."""
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    book = Workbook()
    sheet = book.active
    sheet.title = "chunk"
    for i, column in enumerate(CHUNK_COLUMNS, start=1):
        cell = sheet.cell(row=1, column=i, value=column)
        cell.fill = PatternFill("solid", fgColor=_fill(column))
        cell.font = Font(bold=True)
        cell.alignment = Alignment(horizontal="left")
        # The registry's own description, as the note Excel shows on hover.
        if comment := FIELDS[column].comment:
            cell.comment = _note(comment)
        sheet.column_dimensions[get_column_letter(i)].width = max(11, min(len(column) + 2, 24))
    if examples is EXAMPLES and len(EXAMPLE_NOTES) != len(EXAMPLES):
        raise AssertionError("EXAMPLE_NOTES and EXAMPLES must be parallel")
    for r, row in enumerate(examples, start=2):
        for i, column in enumerate(CHUNK_COLUMNS, start=1):
            sheet.cell(row=r, column=i, value=row.get(column, ""))
        if examples is EXAMPLES:
            sheet.cell(row=r, column=1).comment = _note(EXAMPLE_NOTES[r - 2])
    # Text on every cell of every column, including the empty rows a submitter will type into.
    # `number_format` is per cell in openpyxl, so the range has to cover more than the examples.
    for row in sheet.iter_rows(min_row=1, max_row=len(examples) + 1 + BLANK_ROWS,
                               max_col=len(CHUNK_COLUMNS)):
        for cell in row:
            cell.number_format = "@"
    sheet.freeze_panes = "A2"

    guide = book.create_sheet("columns")
    guide.append([f"How to fill each column: {SPECIFICATION}"])
    guide["A1"].font = Font(bold=True)
    guide.append([])
    guide.append(["column", "group", "description"])
    for cell in guide[3]:
        cell.font = Font(bold=True)
    for column in CHUNK_COLUMNS:
        group = ("required" if _fill(column) == REQUIRED_FILL
                 else "method" if column.startswith("method.")
                 else "meta" if column.startswith("meta.") else "curation")
        guide.append([column, group, FIELDS[column].comment])
    guide.column_dimensions["A"].width = 24
    guide.column_dimensions["B"].width = 10
    guide.column_dimensions["C"].width = 110
    for row in guide.iter_rows(min_row=4, min_col=3, max_col=3):
        for cell in row:
            cell.alignment = Alignment(wrap_text=True, vertical="top")

    book.save(path)
    return path


def _note(text: str):
    from openpyxl.comments import Comment

    note = Comment(text, "vdjdb")
    note.width, note.height = 400, 120
    return note
