# generated by docs/tuning/report.py; do not edit
pooled_TRA_tcremp = 0.3005
median_TRA_tcremp = 0.085
pooled_TRA_tcrnet = 0.2676
median_TRA_tcrnet = 0.0706
pooled_TRB_tcremp = 0.3688
median_TRB_tcremp = 0.0128
pooled_TRB_tcrnet = 0.3198
median_TRB_tcrnet = 0.0142
